#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
FROM zhigui/zigledger-baseimage:_BASE_TAG_

ENV PATH="/usr/local/go/bin/:${PATH}" \
    DEBIAN_FRONTEND="noninteractive" \
    GOPATH="/opt/gopath" \
    PGDATA="/usr/local/pgsql/data/" \
    PGUSER="postgres" \
    PGPASSWORD="postgres" \
    PGSSLCERT="/etc/zhigui/zigledger-ca/ZigledgerTlsClientEEcert.pem" \
    PGSSLKEY="/etc/zhigui/zigledger-ca/ZigledgerTlsClientEEkey.pem" \
    PGVER=_PGVER_ \
    HOSTADDR="127.0.0.1" \
    LDAPPORT="389" \
    LDAPUSER="admin" \
    LDAPPASWD="adminpw" \
    ZIGLEDGER_CA_DATA=/etc/zhigui/zigledger-ca \
    TLS_BUNDLE=ZigledgerTlsPkiBundle.pem \
    TLS_SERVER_CERT=ZigledgerTlsServerEEcert.pem \
    TLS_SERVER_KEY=ZigledgerTlsServerEEkey.pem \
    TLS_CLIENT_CERT=ZigledgerTlsClientEEcert.pem \
    TLS_CLIENT_KEY=ZigledgerTlsClientEEkey.pem \
    MYSQLDATA=/var/lib/mysql

# setup scripts for slapd, postgres, mysql, and openssl
ADD payload/zigledger-ca-fvt.tar.bz2 $ZIGLEDGER_CA_DATA
RUN chmod +x $ZIGLEDGER_CA_DATA/*sh
RUN cd $ZIGLEDGER_CA_DATA
RUN $ZIGLEDGER_CA_DATA/tls_pki.sh
RUN chmod 600 $ZIGLEDGER_CA_DATA/$TLS_SERVER_KEY
RUN chmod 600 $ZIGLEDGER_CA_DATA/$TLS_CLIENT_KEY

# Avoid ERROR:
#   invoke-rc.d: policy-rc.d denied execution of start.
RUN echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d

RUN $ZIGLEDGER_CA_DATA/system_update.sh
RUN $ZIGLEDGER_CA_DATA/postgres_setup.sh
RUN $ZIGLEDGER_CA_DATA/slapd_setup.sh
RUN $ZIGLEDGER_CA_DATA/mysql_setup.sh

# Install zigledger-ca dependencies
RUN go get github.com/go-sql-driver/mysql
RUN go get github.com/lib/pq

# Add docker-built execs for (potentially) alternative architecture
COPY payload/zigledger-ca-client payload/zigledger-ca-server /usr/local/bin/
RUN chmod +x /usr/local/bin/zigledger-ca-client /usr/local/bin/zigledger-ca-server

WORKDIR ${GOPATH}/src/github.com/zhigui/zigledger-ca
RUN cp $ZIGLEDGER_CA_DATA/start.sh /
ENTRYPOINT [ "/start.sh" ]
CMD ["make", "fvt-tests"]
