#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
FROM zhigui/zigledger-tools:_ZIGLEDGER_TAG_
COPY payload/zigledger-ca-client /usr/local/bin
RUN chmod +x /usr/local/bin/zigledger-ca-client
RUN apt-get update
RUN apt-get -y install jq
