#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: "2"

services:
  zigledger-ca-fvt:
    image: zigledger-ca-fvt
    build: .
    command: [make, fvt-tests]
    volumes:
      - ${GOPATH}/src/github.com/zhigui/zigledger-ca:/opt/gopath/src/github.com/zhigui/zigledger-ca
