#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
zigledger-ca:
   image: zhigui/zigledger-ca
   container_name: zigledger-ca
   ports:
     - "7054:7054"
   environment:
     - CA_CERTIFICATE=${CA_CERTIFICATE}
     - CA_KEY_CERTIFICATE=${CA_KEY_CERTIFICATE}
     - ZIGLEDGER_CA_CONFIG=${ZIGLEDGER_CA_CONFIG}
   volumes:
     - /etc/zhigui/zigledger-ca:/var/zhigui/zigledger-ca/config
     - /.zigledger-ca:/var/zhigui/zigledger/.zigledger-ca
   command: sh -c 'sleep 1;zigledger-ca server start -ca /.zigledger-ca/$CA_CERTIFICATE -ca-key /.zigledger-ca/$CA_KEY_CERTIFICATE -config /etc/zhigui/zigledger-ca/$ZIGLEDGER_CA_CONFIG -address "0.0.0.0"'

admin-client:
   image: zhigui/zigledger-ca
   container_name: admin-client
   environment:
     - CSR_CONFIG=${CSR_CONFIG}
   volumes:
     - /etc/zhigui/zigledger-ca:/var/zhigui/zigledger-ca/config
     - /.zigledger-ca:/var/zhigui/zigledger/.zigledger-ca
   command: sh -c "sleep 5;zigledger-ca client enroll admin adminpw http://zigledger-ca:7054 /etc/zhigui/zigledger-ca/$CSR_CONFIG"
   links:
     - zigledger-ca

sdk-client:
   image: zhigui/zigledger-ca
   container_name: sdk-client
   environment:
     - CSR_CONFIG=${CSR_CONFIG}
   volumes:
     - /etc/zhigui/zigledger-ca:/var/zhigui/zigledger-ca/config
     - /.zigledger-ca:/var/zhigui/zigledger/.zigledger-ca
   command: sh -c "sleep 5;zigledger-ca client enroll sdk sdkpw http://zigledger-ca:7054 /etc/zhigui/zigledger-ca/$CSR_CONFIG"
   links:
     - zigledger-ca

bob-client:
   image: zhigui/zigledger-ca
   container_name: bob-client
   environment:
     - CSR_CONFIG=${CSR_CONFIG}
   volumes:
     - /etc/zhigui/zigledger-ca:/var/zhigui/zigledger-ca/config
     - /.zigledger-ca:/var/zhigui/zigledger/.zigledger-ca
   command: sh -c "sleep 5;zigledger-ca client enroll bob bobpw http://zigledger-ca:7054 /etc/zhigui/zigledger-ca/$CSR_CONFIG"
   links:
     - zigledger-ca
